import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const siteDir = path.dirname(fileURLToPath(import.meta.url));
const redirectsPath = path.join(siteDir, '_redirects');
const backendValue = (process.env.OSR_BACKEND_URL || '').trim();

const staticFallbacks = `# Generated by netlify-build.mjs when OSR_BACKEND_URL is not set.
# Static-only mode: keep the built-in site content and explain the missing CMS.
/api/*  /api-unavailable.json  200
/admin  /admin-unavailable.html  200
/admin/ /admin-unavailable.html  200
/admin/* /admin-unavailable.html 200
/*      /index.html            200
`;

if (!backendValue) {
  fs.writeFileSync(redirectsPath, staticFallbacks);
  console.log('[Netlify] OSR_BACKEND_URL is not set; building static-only fallbacks.');
  process.exit(0);
}

let backend;
try {
  backend = new URL(backendValue);
} catch {
  throw new Error('OSR_BACKEND_URL must be a valid backend origin, e.g. https://your-service.onrender.com');
}

const isLocal = ['localhost', '127.0.0.1'].includes(backend.hostname);
if (backend.protocol !== 'https:' && !(isLocal && backend.protocol === 'http:')) {
  throw new Error('OSR_BACKEND_URL must use HTTPS (HTTP is allowed only for localhost testing).');
}
if (backend.username || backend.password || backend.search || backend.hash || !['', '/'].includes(backend.pathname)) {
  throw new Error('OSR_BACKEND_URL must be the backend origin only, without credentials, path, query, or fragment.');
}

const origin = backend.origin;
const proxyRedirects = `# Generated by netlify-build.mjs from OSR_BACKEND_URL.
# Proxy through the Netlify origin so the public site and admin share cookies.
/admin     ${origin}/admin/login.html 200!
/admin/    ${origin}/admin/            200!
/admin/*   ${origin}/admin/:splat 200!
/api/*     ${origin}/api/:splat 200!
/uploads/* ${origin}/uploads/:splat 200!
/*         /index.html              200
`;

fs.writeFileSync(redirectsPath, proxyRedirects);
console.log(`[Netlify] Proxying /admin, /api, and /uploads to ${origin}.`);
