import pg from 'pg';
import { AsyncLocalStorage } from 'node:async_hooks';
import { frontendSource } from '../paths.js';
import { initializeDatabase } from './schema.js';
import { seedFromFrontend } from './seed.js';

// All identifiers here are fixed application tables, never request input.
const tables = 'admins|announcements|board_meetings|initiatives|resources|calendar_events|pages|navigation_items|media|guide_steps|pulse_submissions|pulse_aggregates|activity_logs|site_settings';
const tableReferences = new RegExp(`\\b(FROM|JOIN|INTO|UPDATE|TABLE(?:\\s+IF\\s+NOT\\s+EXISTS)?)\\s+(${tables})\\b`, 'gi');

export function postgresSQL(source) {
  let sql = source
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/datetime\('now'\)/gi, "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')")
    .replace(/date\('now'\)/gi, "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD')")
    .replace(tableReferences, '$1 osr.$2');
  if (/INSERT OR IGNORE INTO/i.test(sql)) {
    sql = sql.replace(/INSERT OR IGNORE INTO/i, 'INSERT INTO').replace(/;?\s*$/, ' ON CONFLICT DO NOTHING');
  }
  let index = 0;
  // Do not rewrite question marks inside quoted strings, identifiers or comments.
  sql = sql.replace(/'(?:''|[^'])*'|"(?:""|[^"])*"|--[^\n]*|\/\*[\s\S]*?\*\/|\?/g, token => token === '?' ? `$${++index}` : token);
  return sql;
}

// The async prepare/get/all/run surface keeps local SQLite and Neon routes alike.
// AsyncLocalStorage pins *all* statements in a transaction to its own client,
// including prepared statements created before the transaction starts.
export class PostgresDatabase {
  context = new AsyncLocalStorage();
  constructor(pool) { this.pool = pool; }
  async query(sql, values = []) {
    return (this.context.getStore() || this.pool).query(sql, values.map(value => typeof value === 'boolean' ? Number(value) : value ?? null));
  }
  prepare(source) {
    const sql = postgresSQL(source);
    return {
      get: async (...values) => (await this.query(sql, values)).rows[0],
      all: async (...values) => (await this.query(sql, values)).rows,
      run: async (...values) => {
        const returning = /^\s*INSERT INTO osr\.navigation_items\b/i.test(sql) ? `${sql} RETURNING id` : sql;
        const result = await this.query(returning, values);
        return { changes: result.rowCount, lastInsertRowid: result.rows[0]?.id };
      },
    };
  }
  exec(source) { return this.query(postgresSQL(source)); }
  transaction(fn) {
    return async (...args) => {
      if (this.context.getStore()) throw new Error('Nested transactions are not supported');
      const client = await this.pool.connect();
      try {
        await client.query('BEGIN');
        const result = await this.context.run(client, () => fn(...args));
        await client.query('COMMIT');
        return result;
      } catch (error) {
        await client.query('ROLLBACK');
        throw error;
      } finally { client.release(); }
    };
  }
  close() { return this.pool.end(); }
}

export async function migrateDatabase(db, sourcePath) {
  await db.transaction(async () => {
    // Concurrent cold starts must not seed the same account/content twice.
    await db.query('SELECT pg_advisory_xact_lock(1869836850)');
    await db.query('CREATE SCHEMA IF NOT EXISTS osr');
    await db.query('CREATE TABLE IF NOT EXISTS osr.schema_migrations (version INTEGER PRIMARY KEY)');
    if (await db.prepare('SELECT version FROM osr.schema_migrations WHERE version=1').get()) return;
    await initializeDatabase(db);
    await seedFromFrontend(db, sourcePath);
    await db.query(`CREATE TABLE IF NOT EXISTS osr.login_attempts (
      key TEXT PRIMARY KEY,
      window_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      attempts INTEGER NOT NULL DEFAULT 1
    )`);
    await db.query('INSERT INTO osr.schema_migrations (version) VALUES (1)');
  })();
}

export async function allowLogin(db, key) {
  // One atomic upsert, shared by all function instances; no in-memory bypass.
  const { rows } = await db.query(`INSERT INTO osr.login_attempts (key) VALUES ($1)
    ON CONFLICT (key) DO UPDATE SET
      attempts = CASE WHEN osr.login_attempts.window_start < CURRENT_TIMESTAMP - INTERVAL '15 minutes' THEN 1 ELSE osr.login_attempts.attempts + 1 END,
      window_start = CASE WHEN osr.login_attempts.window_start < CURRENT_TIMESTAMP - INTERVAL '15 minutes' THEN CURRENT_TIMESTAMP ELSE osr.login_attempts.window_start END
    RETURNING attempts`, [key]);
  await db.query("DELETE FROM osr.login_attempts WHERE window_start < CURRENT_TIMESTAMP - INTERVAL '1 day'");
  return rows[0].attempts <= 20;
}

// PostgreSQL COUNT/SUM(int) return int8. The existing API uses JSON numbers.
const types = new pg.TypeOverrides();
types.setTypeParser(20, value => {
  const number = Number(value);
  if (!Number.isSafeInteger(number)) throw new Error('Database integer exceeds safe JSON range');
  return number;
});
let ready;
export async function getDatabase() {
  if (!ready) {
    ready = (async () => {
      if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
      const url = new URL(process.env.DATABASE_URL);
      if (!['postgres:', 'postgresql:'].includes(url.protocol)) throw new Error('Invalid database protocol');
      const pool = new pg.Pool({
        connectionString: process.env.DATABASE_URL,
        max: 3,
        enableChannelBinding: true,
        connectionTimeoutMillis: 10000,
        idleTimeoutMillis: 10000,
        allowExitOnIdle: true,
        types,
      });
      // Never log connection URLs/passwords or untrusted driver error messages.
      pool.on('error', () => console.error('[CMS] Idle database connection failed'));
      const db = new PostgresDatabase(pool);
      try {
        await migrateDatabase(db, frontendSource);
        return db;
      } catch (error) { await db.close(); throw error; }
    })().catch(error => { ready = undefined; throw error; });
  }
  return ready;
}
